language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: 12
before_script:
  - npm prune
script:
  - npm run all
deploy:
  provider: script
  skip_cleanup: true
  script:
    "npx semantic-release"
